import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import Category from "../components/Category";
import styles from "../styles/Home.module.css";
import About from "../components/About";
import Footer from "../components/Footer";

const Home = () => {
  return (
    <>
      <Head>
        <title>Breaking Bad</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div>
        <div className="absolute z-0">
          <Image src={"/new.jpg"} alt="Home Picture" width={1920} height={865} />
        </div>
        <div className=" relative w-full pt-96 pb-32 pl-36">
          <h1 className="text-2xl text-white mb-2">Get Started</h1>
          <a href="#_" className="relative inline-block text-sm group">
            <span className="relative z-10 block px-5 py-3 overflow-hidden font-medium leading-tight text-gray-800 transition-colors duration-300 ease-out border-2 border-gray-900 rounded-lg group-hover:text-white">
              <span className="absolute inset-0 w-full h-full px-5 py-3 rounded-lg bg-gray-50"></span>
              <span className="absolute left-0 w-48 h-48 -ml-2 transition-all duration-300 origin-top-right -rotate-90 -translate-x-full translate-y-12 bg-gray-900 group-hover:-rotate-180 ease"></span>
              <span className="relative">Explore → </span>
            </span>
            <span
              className="absolute bottom-0 right-0 w-full h-12 -mb-1 -mr-1 transition-all duration-200 ease-linear bg-gray-900 rounded-lg group-hover:mb-0 group-hover:mr-0"
              data-rounded="rounded-lg"
            ></span>
          </a>
        </div>
      </div>
      <Category />
      <About />
      <Footer />
    </>
  );
};
export default Home;
