import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import Category from "../components/Category";
import styles from "../styles/Home.module.css";
import About from "../components/About";

const Home = () => {
  return (
    <>
      <Head>
        <title>Breaking Bad</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <div>
        <Image
          src={"/new.jpg"}
          // src={"/577286.png"}
          alt="Home Picture"
          width={1920}
          height={865}
          className="absolute z-0"
        />
        {/* <h1 className="z-1 m-5">hello</h1> */}
      </div>
      <Category />
      <About />
    </>
  );
};
export default Home;
