import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import Category from "../components/Category";
import styles from "../styles/Home.module.css";

const Home = () => {
  return (
    <>
      <Head>
        <title>Breaking Bad</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Image
        src={"/675486.jpg"}
        // src={"/577286.png"}
        alt="Home Picture"
        width={1920}
        height={1080}
        className=""
      />
      <Category />
    </>
  );
};
export default Home;
